# Generated by Django 4.2 on 2023-05-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_network', '0003_alter_networkobject_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkobject',
            options={'verbose_name': 'Элемент сети', 'verbose_name_plural': 'Элементы сети'},
        ),
        migrations.AlterField(
            model_name='networkobject',
            name='level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='networkobject',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers_network.networkobject', verbose_name='Поставщик'),
        ),
    ]
